Plugins.link("tftSave.dll");

var path = Storages.extractStoragePath(Storages.getPlacedPath("startup.tjs"));

var win = new Window();
var pri = new Layer(win, null);
var lay = new Layer(win, pri);

var savech = 
	(
//		"０１２３４５６７８９ＡＢＣＤＥＦＧＨＩＪＫＬＭＮＯＰＱＲＳＴＵＶＷＸＹＺａｂｃｄｅｆｇｈｉｊｋｌｍｎｏｐｑｒｓｔｕｖｗｘｙｚ"
		"ぁあぃいぅうぇえぉおかがきぎくぐけげこごさざしじすずせぜそぞただちぢっつづてでとどなにぬねのはばぱひびぴふぶぷへべぺほぼぽまみむめもゃやゅゆょよらりるれろゎわゐゑをん"
//		"ァアィイゥウェエォオカガキギクグケゲコゴサザシジスズセゼソゾタダチヂッツヅテデトドナニヌネノハバパヒビピフブプヘベペホボポマミムメモャヤュユョヨラリルレロヮワヰヱヲン"
//		"ヴヵヶ、。，．・：；？！゛゜´｀¨＾°′″ヽヾゝゞ〃仝々〆ー〜…‥‘’“”